language: go

go:
  - 1.5
  - 1.6
  - tip

sudo: false

script:
  - go test $(go list ./... | grep -v vendor)
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c82c1371806bd6eeed4a
    on_success: change
    on_failure: always
    on_start: never   
