language: go
go:
  - 1.11
  - tip 
sudo: false
before_install:
  - echo -e "machine api.github.com\n  login ${GITHUB_LOGIN}\n  password ${GITHUB_TOKEN}" > ~/.netrc
  - chmod 600 ~/.netrc
install:
  - go get -u golang.org/x/vgo
script:
  - vgo test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c82c1371806bd6eeed4a
    on_success: change
    on_failure: always
    on_start: never   
